// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Ksfsvm8qXHmAMfC8YBjpq71qti7DIUY',
    appId: '1:58046617237:web:60048a1b4bf455094fed9c',
    messagingSenderId: '58046617237',
    projectId: 'storeapp-3b378',
    authDomain: 'storeapp-3b378.firebaseapp.com',
    storageBucket: 'storeapp-3b378.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUPBQu9Yc1MI1nX9EyCn2dQs-Da-NIEjU',
    appId: '1:58046617237:android:6b45db229847b2144fed9c',
    messagingSenderId: '58046617237',
    projectId: 'storeapp-3b378',
    storageBucket: 'storeapp-3b378.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvdoFuEGRNfkwx5voFw2v6gDTVB0s8tWk',
    appId: '1:58046617237:ios:c178e4990c892e8d4fed9c',
    messagingSenderId: '58046617237',
    projectId: 'storeapp-3b378',
    storageBucket: 'storeapp-3b378.firebasestorage.app',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvdoFuEGRNfkwx5voFw2v6gDTVB0s8tWk',
    appId: '1:58046617237:ios:c178e4990c892e8d4fed9c',
    messagingSenderId: '58046617237',
    projectId: 'storeapp-3b378',
    storageBucket: 'storeapp-3b378.firebasestorage.app',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Ksfsvm8qXHmAMfC8YBjpq71qti7DIUY',
    appId: '1:58046617237:web:515b44cbe5e359004fed9c',
    messagingSenderId: '58046617237',
    projectId: 'storeapp-3b378',
    authDomain: 'storeapp-3b378.firebaseapp.com',
    storageBucket: 'storeapp-3b378.firebasestorage.app',
  );
}
